E:\Robotics\Robocon 2019\Minitaur\motor_shaft-Static 1
E:\Robotics\Robocon 2019\Minitaur\motor_shaft-Static 1
E:\Robotics\Robocon 2019\Minitaur\motor_shaft-Static 1
E:\Robotics\Robocon 2019\Minitaur\motor_shaft-Static 1
E:\Robotics\Robocon 2019\Minitaur\motor_shaft-Static 1
E:\Robotics\Robocon 2019\Minitaur\motor_shaft-Static 1
E:\Robotics\Robocon 2019\Minitaur\ncrank-Static 1
E:\Robotics\Robocon 2019\Minitaur\ncrank-Static 1
E:\Robotics\Robocon 2019\Minitaur\ncoupler-Static 1
E:\Robotics\Robocon 2019\Minitaur\ncoupler-Static 1
E:\Robotics\Robocon 2019\Minitaur\ncrank-Static 1
E:\Robotics\Robocon 2019\Minitaur\ncoupler-Static 1
E:\Robotics\Robocon 2019\Minitaur\motor_shaft_hub1-Static 1
C:\Users\anike\Documents\Lecture +\Sem 8\MCD 310 Mini Project\Minitaur1.3\joint_part_3-Static 1
C:\Users\anike\Documents\Lecture +\Sem 8\MCD 310 Mini Project\Minitaur1.4\ncoupler-Static 1
C:\Users\anike\Documents\Lecture +\Sem 8\MCD 310 Mini Project\Minitaur1.4\ncrank-Static 1
C:\Users\anike\Documents\Lecture +\Sem 8\MCD 310 Mini Project\Minitaur1.4\motor_shaft_hub1-Static 1
C:\Users\anike\Documents\Lecture +\Sem 8\MCD 310 Mini Project\Minitaur1.4\motor_shaft_hub1-Static 1
