single_leg:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  # Position Controllers ---------------------------------------
  motor_1_position_controller:
    type: effort_controllers/JointPositionController
    joint: motor_1
    pid: {p: 100.0, i: 0.01, d: 1}
  motor_2_position_controller:
    type: effort_controllers/JointPositionController
    joint: motor_2
    pid: {p: 100.0, i: 0.01, d: 1}
